- name: Email report
  uses: dawidd6/action-send-mail@v3
  with:
    server_address: smtp.gmail.com
    server_port: 587
    username: ${{ secrets.EMAIL_USERNAME }}
    password: ${{ secrets.EMAIL_PASSWORD }}
    subject: Quarterly Crypto Capital Flow Report
    to: martim.salgado@rte.pt
    from: ${{ secrets.EMAIL_USERNAME }}
    body: |
      Hello Martim,

      Please find attached your quarterly crypto capital flow report.

      Best,
      Your Automated Analyst
    attachments: crypto_report.pdf
